### ISSUE TITLE
Signalp 'Sequence limit reached: Max 10000 sequences are allowed'

### ISSUE THREAD

**Issue by flaviaariany** [fteufel/signalp-6.0#10]
Hello,

I am trying to run signalp on a fasta file with 258514 sequences. However, I reached the number of sequences limit. 
How can I increase the sequence limit in SignalP?

Thanks.

**Comment by fteufel** [comment]
Hi,

I guess you encountered this limit when using the DTU server? You could download the installable version that doesn't have limitations. Or split up your fasta file into smaller ones if you want to stick to the online version.
