### ISSUE TITLE
Limit the number of threads

### ISSUE THREAD

**Issue by rattei** [fteufel/signalp-6.0#11]
Users are running signalp-6.0 on our compute cluster. Each signalp process takes as many CPU cores as the hardware provides. The processes scale poorly if using >8 threads, especially if using more than 64 threads. Please provide a command line parameter that allows the user to define the number of CPU threads that signalp uses.

**Comment by fteufel** [comment]
Hi @rattei I'll work on including that. 

For now you could ask users to try to specify the `OMP_NUM_THREADS` environment variable to limit thread usage.
(https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html)

**Comment by rattei** [comment]
I have just defined the number of threads in predict.py, sequential_model.py, utils.py, conversion_utils/move_checkpoint_to_device.py by adding a line after PyTorch is imported:
"import torch
torch.set_num_threads(8)"
This fix has solved the problem for me, but needs to be sustained in the code, please.

According to my tests, up to 8 threads scale well. More threads scale less well, so we split the input into chunks and run hundreds of signalp commands in a job array.
