### ISSUE TITLE
Mode `slow` not found, running `slow-sequential` instead.

### ISSUE THREAD

**Issue by barthelemymp** [fteufel/signalp-6.0#13]
The mode slow does not seem to work:
my command is:
`signalp6 --fastafile /home/barthelemy/beta/A.fasta --organism other --output_dir /home/barthelemy/beta/signalP_out --format txt --mode slow`

Does slow-sequential produce the same output as slow ? 

best

barthelemy

**Comment by fteufel** [comment]
Hi Barthelemy,
This is fine, it gives the same output. We decided to ship a version that runs the slow model sequentially, as it's too big for most systems when running in parallel.
