### ISSUE TITLE
Can't use online service

### ISSUE THREAD

**Issue by Axolotl233** [fteufel/signalp-6.0#14]
Hi community,

Signalp-6.0 is a wonderful tool, but I can't access to the website (https://services.healthtech.dtu.dk/service.php?SignalP-6.0.)  for online service. Is there anything wrong here?

Thanks,
Nemo

**Comment by fteufel** [comment]
Hi Nemo,

I'm also having problems accessing it today - hope it will be back soon. In the meantime, our mirror at https://biolib.com/DTU/SignalP-6/ is working.

Will close this once DTU is back.
