### ISSUE TITLE
Can not find ensemble_model_signalp6.pt file

### ISSUE THREAD

**Issue by arminmm91** [fteufel/signalp-6.0#16]
I've installed Signal-6.0, but when running the command on my fasta file, it gives an error: FileNotFoundError: Slow mode requires the full model to be installed at ....., I'm looking for ensemble_model_signalp6.pt to resolve this error. 

Please if you have any opinion or solution on this error let me know.

**Comment by fteufel** [comment]
Hi, could you show me your full command, and the complete error message?

**Comment by arminmm91** [comment]
this is the full command plus the error:
(signalp_env) (base) armin@B22305:/mnt/d/databases/signalp6_slow_sequential/signalp-6-package$ signalp6 --fastafile /mnt/d/databases/final_representetive_protein.fasta --organism eukarya --output_dir /mnt/d/databases/signal_output/ --format txt --mode slow


Traceback (most recent call last):
  File "/mnt/d/databases/signalp6_slow_sequential/signalp_env/lib/python3.10/site-packages/signalp6-6.0+g-py3.10.egg/signalp/predict.py", line 208, in main
    model = torch.jit.load(SLOW_MODEL_PATH)
  File "/mnt/d/databases/signalp6_slow_sequential/signalp_env/lib/python3.10/site-packages/torch-2.0.0-py3.10-linux-x86_64.egg/torch/jit/_serialization.py", line 152, in load
    raise ValueError("The provided filename {} does not exist".format(f))  # type: ignore[str-bytes-safe]
ValueError: The provided filename /mnt/d/databases/signalp6_slow_sequential/signalp_env/lib/python3.10/site-packages/signalp6-6.0+g-py3.10.egg/signalp/model_weights/ensemble_model_signalp6.pt does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/d/databases/signalp6_slow_sequential/signalp_env/bin/signalp6", line 33, in <module>
    sys.exit(load_entry_point('signalp6==6.0+g', 'console_scripts', 'signalp6')())
  File "/mnt/d/databases/signalp6_slow_sequential/signalp_env/lib/python3.10/site-packages/signalp6-6.0+g-py3.10.egg/signalp/__init__.py", line 6, in predict
    main()
  File "/mnt/d/databases/signalp6_slow_sequential/signalp_env/lib/python3.10/site-packages/signalp6-6.0+g-py3.10.egg/signalp/predict.py", line 217, in main
    raise FileNotFoundError(f"Slow mode requires the full model to be installed at {SLOW_MODEL_PATH}. Missing from this installation or incorrectly configured.")
FileNotFoundError: Slow mode requires the full model to be installed at /mnt/d/databases/signalp6_slow_sequential/signalp_env/lib/python3.10/site-packages/signalp6-6.0+g-py3.10.egg/signalp/model_weights/ensemble_model_signalp6.pt. Missing from this installation or incorrectly configured.

**Comment by fteufel** [comment]
Could you try  `--mode slow-sequential` ?
I'll have to check why this happens, the tool should default to this if ensemble_model_signalp6.pt is not found.

**Comment by arminmm91** [comment]
No, did not work, please see the error:
//mnt/d/databases/signalp6_slow_sequential/signalp-6-package$ signalp6 --fastafile /mnt/d/databases/final_representetive_protein.fasta --organism eukarya --output_dir /mnt/d/databases/signal_output/ --format txt --mode slow-sequential
Traceback (most recent call last):
  File "/mnt/d/databases/signalp6_slow_sequential/signalp_env/bin/signalp6", line 33, in <module>
    sys.exit(load_entry_point('signalp6==6.0+g', 'console_scripts', 'signalp6')())
  File "/mnt/d/databases/signalp6_slow_sequential/signalp_env/lib/python3.10/site-packages/signalp6-6.0+g-py3.10.egg/signalp/__init__.py", line 6, in predict
    main()
  File "/mnt/d/databases/signalp6_slow_sequential/signalp_env/lib/python3.10/site-packages/signalp6-6.0+g-py3.10.egg/signalp/predict.py", line 220, in main
    raise FileNotFoundError(f'Sequential mode requires the models to be installed at {SEQUENTIAL_MODEL_PATH}. Missing from this installation.')
FileNotFoundError: Sequential mode requires the models to be installed at /mnt/d/databases/signalp6_slow_sequential/signalp_env/lib/python3.10/site-packages/signalp6-6.0+g-py3.10.egg/signalp/model_weights/sequential_models_signalp6. Missing from this installation.

**Comment by fteufel** [comment]
Could it be that you installed the fast version?

**Comment by arminmm91** [comment]
No, I'm certain that I'm using slow version

**Comment by fteufel** [comment]
Then I assume the copy command from the installation instructions must have failed.
Could you try running this again, and then checking that the path that is `SIGNALP_DIR` matches what you've seen in the error message, as well as the contents of it after running the command?
```
SIGNALP_DIR=$(python3 -c "import signalp; import os; print(os.path.dirname(signalp.__file__))" )
cp -r signalp-6-package/models/* $SIGNALP_DIR/model_weights/
```

**Comment by arminmm91** [comment]
I manually copied the files into that directory pointed out in the error, and the code is running. I know it has been frequently suggested to do not transfer files manually but I was tired of trying.

**Comment by fteufel** [comment]
Great! The command should have taken care of this, but doing it manually is totally fine.

**Comment by fteufel** [comment]
SignalP doesn't involve a search step and there are no databases - the eukarya flag is simply there to prevent the tool from predicting signal peptide types that only exist in bacteria and archaea.

**Comment by yangruixue-xue** [comment]
> 那我猜安装说明里的复制命令一定失败了。你能不能再试一次，然后检查路径是否符合你在错误信息中看到的，以及执行命令后的内容？`SIGNALP_DIR`
> 
> ```
> SIGNALP_DIR=$(python3 -c "import signalp; import os; print(os.path.dirname(signalp.__file__))" )
> cp -r signalp-6-package/models/* $SIGNALP_DIR/model_weights/
> ```

I downloaded the software package from the official website and compressed it, but the model folder only contains these weight files: averaged_viterbi.pt, test_0_val_1.pt, test_0_val_2.pt, test_1_val_0.pt, test_1_val_2.pt, test_2_val_0.pt, test_2_val_1.pt. Then I followed this reply to run it, and it worked. Thank you very much, and I also hope that others can benefit from my experience.
