### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by samavinasir96** [fteufel/signalp-6.0#18]
The package is not installing via the command "pip install signalp-6-package/"_. When I installed it via "python setup.py install" command, no "signalp-6-package/models/" directory was found and no model files were present in any folder of the directory. Consequently, the package is not running well. 
It used to work nice before when i installed it on my system a few months ago, package was installed via "pip install signalp-6-package/" and upon installing "signalp-6-package/models/" directory was created in which i copied the model file "distilled_model_signalp6.pt" to "signalp/model_weights/" directory and then pkg started running. I am facing errors in the same steps now! 
I would appreciate the help you would provide, as I am in need of this python package. Awaiting your kind response.

**Comment by fteufel** [comment]
Hi @samavinasir96, I'm not sure I understand the error that you are facing. What is the traceback from `pip install signalp-6-package/` ?

I can assure you that signalp6 itself hasn't changed in the recent months, so it should still work the same on the same system.

**Comment by samavinasir96** [comment]
The traceback is : ERROR: Invalid requirement: 'signalp-6-package/'

**Comment by fteufel** [comment]
Hi, this seems odd, and unspecific for signalp6 itself. Are you sure that you are in the right directory, and the python installation is in order?

**Comment by samavinasir96** [comment]
Actually i have a directory which has an activated virtual environment and has many other python packages installed. I want to install it in that directory. when i run the command in that directory it says; 
ERROR: Directory 'signalp-6-package/' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
and when i enter the folder where setup.py file is present it says:
ERROR: Invalid requirement: 'signalp-6-package/'

**Comment by fteufel** [comment]
You need to run the command from the parent directory that contains `signalp-6-package`. 
Are you sure that this directory is uncorrupted and has the contents from the original download? Both files `setup.py` and `pyproject.toml` should be there.

**Comment by samavinasir96** [comment]
the directory is uncorrupted as remaining all the packages i downloaded are working well. i downloaded this package via github cli "gh repo clone fteufel/signalp-6.0"  into the directory. "setup.py" is present but no "pyproject.toml" is present there.

**Comment by fteufel** [comment]
You are using the wrong package. The github repo is the research codebase, you probably want the prediction package available from DTU https://services.healthtech.dtu.dk/service.php?SignalP-6.0

**Comment by samavinasir96** [comment]
Yes i need the service https://services.healthtech.dtu.dk/services/SignalP-6.0/. But I am in need of its python package, not web based service.

**Comment by fteufel** [comment]
You can click on "Downloads" there to get the package.

**Comment by samavinasir96** [comment]
OK.. I got the right package. Thank You!
i have another query now! the model file "distilled_model_signalp6.pt" is very heavy, around 1.5gb in size. I have to install the package on a shared cloud which has limited resources. The package installed on local system, but due to its large size, it is creating issues there! 
Can you please provide me with a solution for this ?

**Comment by fteufel** [comment]
Unfortunately not. There's no workaround for storing the file, signalp6 depends on it and needs to load it when running.
