### ISSUE TITLE
Model error?

### ISSUE THREAD

**Issue by B10inform** [fteufel/signalp-6.0#2]
Hi,

SignalP6 is out and it looks great. I started to work on it but getting following error.

**Installed as follow:**
python3 -m pip install signalp-6-package/

SIGNALP_DIR=$(python3 -c "import signalp; import os; print(os.path.dirname(signalp.__file__))" )
cp -r signalp-6-package/models/* $SIGNALP_DIR/model_weights/

**signalp6 -fasta /path/to/input.fasta -org euk --output_dir path/to/be/saved --format txt --mode slow**

Traceback (most recent call last):
File "/home/.local/lib/python3.6/site-packages/signalp/predict.py", line 207, in main
    model = torch.jit.load(SLOW_MODEL_PATH)
  File "/home/.local/lib/python3.6/site-packages/torch/jit/_serialization.py", line 151, in load
    raise ValueError("The provided filename {} does not exist".format(f))  # type: ignore[str-bytes-safe]
ValueError: The provided filename /home/.local/lib/python3.6/site-packages/signalp/model_weights/ensemble_model_signalp6.pt does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/.local/bin/signalp6", line 8, in <module>
    sys.exit(predict())
  File "/home/.local/lib/python3.6/site-packages/signalp/__init__.py", line 6, in predict
    main()
  File "/home/.local/lib/python3.6/site-packages/signalp/predict.py", line 211, in main
    raise FileNotFoundError(f"Slow mode requires the full model to be installed at {SLOW_MODEL_PATH}. Missing from this installation or incorrectly configured.")
FileNotFoundError: Slow mode requires the full model to be installed at /home/.local/lib/python3.6/site-packages/signalp/model_weights/ensemble_model_signalp6.pt. Missing from this installation or incorrectly configured.

I could not find the model "ensemble_model_signalp6.pt" where can i download it from?
The model present is "sequential_models_signalp6".

Thanks

**Comment by fteufel** [comment]
Hi, 
please try this instead:
```
signalp6 -fasta /path/to/input.fasta -org euk --output_dir path/to/be/saved --format txt --mode slow-sequential
```
This mode means that the "slow" model is run sequentially, as the default parallel version is too memory-hungry for most systems. The prediction output is exactly the same. If you really want the `slow` mode and your system can handle it, you can download it at https://mega.nz/file/TFUmSZxT#sQWPIlHtkWLJ1otfqxx1zeERUUu4D4YM3yvWefTXnUU

**Comment by B10inform** [comment]
Thank you, its running now.
