### ISSUE TITLE
how and from where to download the model files

### ISSUE THREAD

**Issue by gunjanpandey** [fteufel/signalp-6.0#21]
pls tell

**Comment by ransenyu** [comment]
I found it in readme.txt:
Download the model weights you need at 
 - slow, memory-hungry (parallel) model at https://mega.nz/file/TFUmSZxT#sQWPIlHtkWLJ1otfqxx1zeERUUu4D4YM3yvWefTXnUU (or at DTU)
 - fast model at https://mega.nz/file/uZ0DVQ7b#oDDerv_8mJmj1ypC_CX8OaWBxfYe4dXDvHGVgOiwCks (or at DTU)
 - slow, memory-saving (sequential) model for now only hosted at DTU.
