### ISSUE TITLE
time to run signalp6/6.0h

### ISSUE THREAD

**Issue by Alecrim24** [fteufel/signalp-6.0#22]
Hi there,

im running this software as part of a workflow to eventually generate a trinotate.xls.

However the issue im facing is time. My script has been running for 4 days and a bit and the max is 7 days.

is there a way to do this in sections so it can continue running

or

if i submit the script again will it be able to remember where it left from and continue.

kind regards

George

**Comment by fteufel** [comment]
Hi,
I don't know about your script and workflow, so can't really comment on that. How big is your job? I would recommend using GPUs for large job as it's much faster.

If you cancel a `signalp6` command it will not restart from where it was. The best way to split large jobs is to make multiple input fasta files and predict them one by one.
