### ISSUE TITLE
Code to reproduce the restricted single linkage clustering results?

### ISSUE THREAD

**Issue by brush111111111111** [fteufel/signalp-6.0#23]
Is the code for the restricted single linkage clustering of the dataset available? Thank you very much.

**Comment by fteufel** [comment]
Hi,

Yes, it is, we have published the clustering approach as its own method now: https://github.com/graph-part/graph-part

The main change that was made in comparison to what is described in the SP6 paper is that we have replaced ggsearch36 with needleall for pairwise alignment.
