### ISSUE TITLE
slow model download website is not available 

### ISSUE THREAD

**Issue by Tomer-Tsaban** [fteufel/signalp-6.0#26]
Hi,
thanks for this wonderful tool.

unfortunately when trying to download the slow model from the provided link, i get the error:
the fast model donwload works fine. 
is it possible to update the download site \ download from a different source? 
thanks!
![image](https://github.com/fteufel/signalp-6.0/assets/32357066/16bfcee9-2ad8-40b5-a27f-7becc06f0d88)

**Comment by Tomer-Tsaban** [comment]
I now realize that the relevant model was added in the downloaded package from the DTU website (after signing with an academic user). If that is the case, i think it would be helpful to update the installation readme to be more clear. 

thanks!

**Comment by fteufel** [comment]
Hi, had not noticed these went offline - I'll remove them from the readme.

**Comment by Rohit-Satyam** [comment]
@fteufel You haven't removed the links from the readme. Besides, I can not find slow `ensemble_model_signalp6.pt` in the tar file I downloaded from the website
