### ISSUE TITLE
output processed_entries contains all the proteins with or without the signal

### ISSUE THREAD

**Issue by JulieRamMar** [fteufel/signalp-6.0#27]
Hello, 

I am using signalP6 but I am having a hard time retrieving the proteins that are supposed to have the P signal in the files named "processed_entries", as I understood from previous versions of the program, these files were supposed to contain only the proteins that are predicted to have the P signal, but with their signal peptide sequences removed. But instead I get a fasta, although without the ">" in the header name, which contains all the proteins I provided as input, although in the "prediction_results.txt" file it is clear that not all the proteins provided carry the signal. This file looks like this: 

# SignalP-6.0	Organism: Eukarya	Timestamp: 20240212172549
# ID	Prediction	OTHER	SP(Sec/SPI)	CS Position
FRA0004_1	NO_SP	1.000040	0.000000	
FRA0004_2	NO_SP	1.000039	0.000004	
FRA0004_3	SP	0.000306	0.999679	CS pos: 18-19. Pr: 0.9627
FRA0004_4	NO_SP	1.000064	0.000000	
.
.
.

But the "fasta" file looks like this:

FRA0004_1
MKDIVSAISHRFHGLSKSKAAV...
FRA0004_2
MEGLRRSLIEGSSSEKYSVYNP...
FRA0004_3
MKTSSVLALASFAAFATASPIAP...
FRA0004_4
MKFGTTLRKSVYAPWKDKYID...
FRA0004_5
MDTPPRVFETAVGKFWR ...
.
.
.

I really appreciate any help that you can provide to solve this,

Thank you so much

**Comment by fteufel** [comment]
Hi, which version of signalp6 are you running?

**Comment by JulieRamMar** [comment]
Hi, it's the 6.0

**Comment by fteufel** [comment]
The issue you're seeing was fixed starting from version 6.0g, so I assume that an older version is running on the cluster, and we can fix it by updating. Maybe you could ask the cluster admin to replace the installation with the most recent version that is available for download at DTU?
