### ISSUE TITLE
ValueError: not enough values to unpack in LargeCRFPartitionDataset

### ISSUE THREAD

**Issue by carolinalvarez** [fteufel/signalp-6.0#28]
Hi,

I cloned the repository to my local machine and I'm trying to run the `main_training_loop` function with the provided example data (`example_seqs.fasta`) using the default parameters. However, I'm encountering a `ValueError`, which seems to occur during the initialization of the `LargeCRFPartitionDataset` class in the `train_model.py` script.

Here is the code I used:

````
args = Namespace(
    data=example_fasta,
    sample_weights=None,
    test_partition=0,
    validation_partition=1,
    lr=0.01,
    clip=0.25,
    epochs=10,
    batch_size=32,
    wdecay=1.2e-6,
    optimizer="adam",
    output_dir="SPs-project/output",
    resume="Rostlab/prot_bert", 
    experiment_name="BERT-CRF-Experiment",
    crossval_run=False,
    log_all_final_metrics=False,
    num_seq_labels=37,
    num_global_labels=6,
    global_label_as_input=False,
    region_regularization_alpha=0,
    lm_output_dropout=0.1,
    lm_output_position_dropout=0.1,
    use_sample_weights=False,
    use_random_weighted_sampling=False,
    positive_samples_weight=None,
    average_per_kingdom=False,
    crf_scaling_factor=1.0,
    use_weighted_kingdom_sampling=False,
    random_seed=42,
    additional_train_set=None,
    model_architecture="bert_prottrans",
    remove_top_layers=0,
    kingdom_embed_size=0,
    use_cs_tag=False,
    kingdom_as_token=False,
    sp_region_labels=False,
    constrain_crf=False
)

tm.main_training_loop(args)

24/08/10 01:15:28 - INFO - train_model -   torch seed: 42
24/08/10 01:15:28 - INFO - train_model -   Saving to [folder]
24/08/10 01:15:28 - INFO - train_model -   Loading pretrained model in Rostlab/prot_bert
Some weights of BertSequenceTaggingCRF were not initialized from the model checkpoint at Rostlab/prot_bert and are newly initialized: ['crf._constraint_end_mask', 'crf._constraint_mask', 'crf._constraint_start_mask', 'crf.end_transitions', 'crf.start_transitions', 'crf.transitions', 'outputs_to_emissions.bias', 'outputs_to_emissions.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
24/08/10 01:15:29 - INFO - train_model -   Loaded weights from Rostlab/prot_bert for model bert
24/08/10 01:15:29 - INFO - train_model -   Training on [2, 3, 4, 5, 6, 7, 8, 9], validating on 1

ValueError: not enough values to unpack (expected 4, got 1)

````

I've tried to run it with a larger dataset (a random sample of the `train_set.fasta`, but I keep having the same issue. It would be great if you could provide some guidance on how to solve this problem.

Thanks!

Best,
Carolina

**Comment by fteufel** [comment]
Hi,

that part of the codebase is likely broken and deprecated. As indicated in the example command, all models were trained with `sp_region_labels=True`.

**Comment by carolinalvarez** [comment]
Thanks for your reply, I updated it and tried with the example command. It runs with the train_set.fasta, but I get the same error when I try using a different dataset.  I ran it with a random subset of train_set.fasta (to have a sense of running time with a smaller dataset, as I would like to run my data at some point). I create the random subset like this:

```
random.seed(42)
desired_count = 300
random_seqs = []

for kingdom, sequences in kingdom_seqs.items():
    num_to_sample = round((len(sequences) / total_sequences) * desired_count)
    random_seqs.extend(random.sample(sequences, num_to_sample))

SeqIO.write(random_seqs, random_fasta, 'fasta')
```

and check that it has the same kingdom distribution as the original

![image](https://github.com/user-attachments/assets/dcadaac3-0c5a-4ea7-bac6-94f0bf215dc9)

However, when I run ``` python3 scripts/train_model.py --data data/random_seqs.fasta --test_partition 0 --validation_partition 1 --output_dir testruns --experiment_name testrun1 --remove_top_layers 1 --kingdom_as_token --sp_region_labels --region_regularization_alpha 0.5 --constrain_crf --average_per_kingdom ```, I get:

```
ValueError: not enough values to unpack (expected 4, got 1)
```

The error comes from the `subset_dataset` function in `datasets.py` during the unpacking of parsed identifiers into acc_ids, kingdom_ids, type_ids, and partition_ids (line 79).  I added a print statement to inspect the parsed variable before the unpacking

```
['P0C0V8', 'EUKARYA', 'NO_SP', '1']
['Q9UK73', 'EUKARYA', 'NO_SP', '2']
['Q8K202', 'EUKARYA', 'NO_SP', '1']
...
```
These entries all split into four components, yet the error persists.

**Comment by fteufel** [comment]
Ok, and the print statement looks basically the same for the full train_set.fasta?

**Comment by carolinalvarez** [comment]
I see. You are right, SeqIO cannot take the 3-line format into account. What does the 3rd line label stand for in your train dataset? Since I would like to train SignalP6 with my data using the source code, I would have to adapt it to this 3-line format.

**Comment by fteufel** [comment]
The format is documented on the data tab of the SignalP site https://services.healthtech.dtu.dk/services/SignalP-6.0/

```
>Uniprot_AC|Kingdom|Type|Partition No
amino-acid sequence
annotation [S: Sec/SPI signal peptide | T: Tat/SPI or Tat/SPII signal peptide | L: Sec/SPII signal peptide | P: Sec/SPIII signal peptide | I: cytoplasm | M: transmembrane | O: extracellular]
```

**Comment by carolinalvarez** [comment]
Thanks a lot for the link and example, I was indeed missing one line for my subset.
