### ISSUE TITLE
I don't have sequential_models_signalp6 file

### ISSUE THREAD

**Issue by Niohuruzh** [fteufel/signalp-6.0#29]
I downloaded `signalp-6.0h.slow_sequential.tar.gz` and installed the software following the instructions in `README.md`. However, when I ran the command: `signalp6 --fastafile 02.proteins.fa --output_dir 02 --organism eukarya --mode slow-sequential`, I encountered an error. I tried to locate the `sequential_models_signalp6` file in the `signalp-6-package` directory, but it is missing. How can I resolve this issue?

> Traceback (most recent call last):
>   File "/home/anaconda3/envs/signalp/bin/signalp6", line 8, in <module>
>     sys.exit(predict())
>   File "/home/anaconda3/envs/signalp/lib/python3.7/site-packages/signalp/__init__.py", line 6, in predict
>     main()
>   File "/home/anaconda3/envs/signalp/lib/python3.7/site-packages/signalp/predict.py", line 228, in main
>     raise FileNotFoundError(f'Sequential mode requires the models to be installed at {sequential_model_path}. Missing from this installation.')
> FileNotFoundError: Sequential mode requires the models to be installed at /home/anaconda3/envs/signalp/lib/python3.7/site-packages/signalp/model_weights/sequential_models_signalp6. Missing from this installation.

Looking forward your reply
Best regards!

**Comment by fteufel** [comment]
Hi, so you're saying the tar.gz download did not contain model files in`signalp-6-package/models` ?

**Comment by Niohuruzh** [comment]
Hi,
Thanks for you reply. The `signalp-6-package` contain `models`

> $ ls signalp-6-package/models
  README.md  sequential_models_signalp6

> $ ls sequential_models_signalp6
 averaged_viterbi.pt  test_0_val_1.pt  test_0_val_2.pt  test_1_val_0.pt  test_1_val_2.pt  test_2_val_0.pt  test_2_val_1.pt

Looking forward your reply
Best regards!

**Comment by Niohuruzh** [comment]
Hi,
Thanks for your reply.
I figure out  what was happening with my environment. When I use `SIGNALP_DIR=$(python3 -c "import signalp; import os; print(os.path.dirname(signalp.__file__))" )` in different directory, the value of `$SIGNALP_DIR` changed. This led to a mistake with the `cp` command. I corrected the $SIGNALP_DIR, and now the code is running successfully.

Thanks again!
