### ISSUE TITLE
Minor updates required

### ISSUE THREAD

**Issue by Rohit-Satyam** [fteufel/signalp-6.0#30]
I see that the README files require update where you remove `slow, memory-hungry (parallel) model at https://mega.nz/file/TFUmSZxT#sQWPIlHtkWLJ1otfqxx1zeERUUu4D4YM3yvWefTXnUU (or at DTU)` expired links. 

Besides, I downloaded `signalp-6.0h.fast.tar.gz` and realized it lacks `ensemble_model_signalp6.pt` file. This file is also absent from the slow-sequential version. In an old [issue](https://github.com/fteufel/signalp-6.0/issues/16)  you said it should be taken care of automatically, but it's not being taken care of automatically

```
time signalp6 --fastafile test.fa --organism eukarya --output_dir . --model_dir signalp-6-package/models/ --format txt --mode slow
```

Currently, I am handling this by changing the name of the `distilled_model_signalp6` to `ensemble_model_signalp6` as described by RosettaFold people [here](https://github.com/baker-laboratory/RoseTTAFold-All-Atom/blob/main/README.md) but can you confirm if this is the right approach because as per my observation the runtime didn't change at all so changing the mode to `slow` while using the model made for `fast` mode is useless right?

**Comment by fteufel** [comment]
Hi, `ensemble_model_signalp6.pt` has been discontinued. If you want to use the slow model, please download `slow_sequential` from DTU.

Yes, renaming it doesn't work - that just means that the fast model will be run under a wrong name.
