### ISSUE TITLE
SignalP6 reports less number of proteins with signal peptide

### ISSUE THREAD

**Issue by Rohit-Satyam** [fteufel/signalp-6.0#31]
Hi @fteufel 

I realized that there are 119 proteins in my organism PfalciparumNF54 that were previously predicted to have signal peptide by Signalpv5 but are predicted to not have by Signalp6. For instance, `PfNF54_010006200` is predicted to have SP by SignalPv5 as can be seen below:

![image](https://github.com/user-attachments/assets/66d542a6-6beb-49bf-bf3f-08bf8e2167dd)

Signalp6

![image](https://github.com/user-attachments/assets/fe5de5eb-3377-409e-a55b-95bdda8ebd9c)

Which one should I trust?

**Comment by fteufel** [comment]
Hi,

it's hard to answer this question in general. Based on our evaluations, SignalP6 is more accurate than SignalP5 _overall_. Whether this is the case on a micro level in Plasmodium, I cannot say, we haven't done any organism-specific evaluations. 

I think it is known that Apicomplexa signal peptides are very hard to predict correctly for most algorithms.
