### ISSUE TITLE
Feature request: Include the current package version

### ISSUE THREAD

**Issue by darcyabjones** [fteufel/signalp-6.0#4]
Hi there!

Thanks again for your great work.
It would be really helpful if the distributed package could please have the current version numbers in them please!

I maintain a pipeline that runs SignalP6 (https://github.com/ccdmb/predector), and i've been getting bug reports from people.
It would be helpful to know exactly which version of signalp 6 is actually installed, so that I know whether to report a new bug to you or ask them to update.

It also helps me to cache pre-computed results, and automatically skip repeated analysis if an identical version has been run before.

Currently the `-h` `--help` flag lists `usage: SignalP 6.0 Signal peptide prediction tool [-h] --fastafile FASTAFILE`.
And `setup.py` lists `version='1.0'`.

It would be helpful if you could tag the full version info e.g. `6.0e` in these places.
Or a special `--version` flag is becoming more common.

I use the [bump2version](https://github.com/c4urself/bump2version) to do this automatically with a git tag for me.

I know this is pretty low priority so feel absolutely free to say no.
It would just be helpful.

Thanks and all the best,

Darcy

**Comment by fteufel** [comment]
Included in 6.0f
