### ISSUE TITLE
Wrong column name (typo) in `prediction_results.txt`

### ISSUE THREAD

**Issue by ealdraed** [fteufel/signalp-6.0#6]
Hello,

I just ran the downloaded version of SignalP 6.0g and noticed that the TATLIPO column in `prediction_results.txt` (printed by `make_output_files.py:21`) reads "TATLIPO(Sec/SPII)" where it supposedly should output "TATLIPO(Tat/SPII)".

Best regards

**Comment by fteufel** [comment]
Thanks for reporting this! Seems this went unnoticed for quite a long time now. Will be fixed in the next patch.

**Comment by fteufel** [comment]
fixed
