### ISSUE TITLE
Can signaIP-6.0 applied to prediction on SRP-dependent signal sequences?

### ISSUE THREAD

**Issue by ddd9898** [fteufel/signalp-6.0#9]
Hi, I found that signaIP-6.0 was trained to identify signal peptides of Sec or Tat pathway. However, when I tested signaIP-6.0 on the secreted protein DSBA_ECOLI which is reported to be SRP-dependent, I get the following output:
![1](https://user-images.githubusercontent.com/74239179/200860396-67a9b2b2-b3e7-45ba-a750-f1884aee2005.png)

It surprised me that the signal sequence was identified quite well, consistent with the reported one. But the signal peptide of DSBA_ECOLI is also classified to the Sec pathway. I think this phenomenon is interesting. Could you give some possible explanations?

**Comment by fteufel** [comment]
Hi,
SRP-recognized peptides also use the Sec pathway in the sense that they are also translocated by the Sec translocon. We therefore treat SRP and SecA recognized peptides as the same class.
